# Generated by Django 2.0.3 on 2019-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('topping_1', models.CharField(max_length=64)),
                ('topping_2', models.CharField(max_length=64)),
                ('topping_3', models.CharField(max_length=64)),
                ('topping_4', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
    ]
