# Generated by Django 2.0.3 on 2019-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian'), ('Ham + Cheese', 'Ham + Cheese'), ('Meatball', 'Meatball'), ('Tuna', 'Tuna'), ('Turkey', 'Turkey'), ('Chicken Parmigiana', 'Chicken Parmigiana'), ('Eggplant Parmigiana', 'Eggplant Parmigiana'), ('Steak', 'Steak'), ('Steak + Cheese', 'Steak + Cheese'), ('Sausage, Peppers & Onions', 'Sausage, Peppers & Onions'), ('Hamburger', 'Hamburger'), ('Cheeseburger', 'Cheeseburger'), ('Fried Chicken', 'Fried Chicken'), ('Veggie', 'Veggie')], max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('steak_adds', models.CharField(choices=[('Mushrooms', 'Mushrooms'), ('Green Peppers', 'Green Peppers'), ('Onions', 'Onions')], max_length=64)),
                ('extra_cheese', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sort',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping_1',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicke', 'Buffalo Chicke'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping_2',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicke', 'Buffalo Chicke'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping_3',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicke', 'Buffalo Chicke'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping_4',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicke', 'Buffalo Chicke'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], max_length=64),
        ),
    ]
