# Generated by Django 2.0.3 on 2019-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190118_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Baked Ziti', 'Baked Ziti'), ('Meatball Parm', 'Meatball Parm'), ('Chicken Parm', 'Chicken Parm')], max_length=64)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('Baked Ziti w/Mozzarella', 'Baked Ziti w/Mozzarella'), ('Baked Ziti w/Meatballs', 'Baked Ziti w/Meatballs'), ('Baked Ziti w/Chicken', 'Baked Ziti w/Chicken')], max_length=64)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Salad w/Tuna', 'Salad w/Tuna')], max_length=64)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='subs',
            name='steak_adds',
            field=models.CharField(blank=True, choices=[('Mushrooms', 'Mushrooms'), ('Green Peppers', 'Green Peppers'), ('Onions', 'Onions')], max_length=64),
        ),
    ]
