# Generated by Django 2.0.3 on 2019-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190121_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platters',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default=1, max_length=64),
            preserve_default=False,
        ),
    ]
