# Generated by Django 2.0.3 on 2019-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dinner_platters_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('topping_1', models.CharField(blank=True, max_length=64)),
                ('topping_2', models.CharField(blank=True, max_length=64)),
                ('topping_3', models.CharField(blank=True, max_length=64)),
                ('topping_4', models.CharField(blank=True, max_length=64)),
                ('extra_cheese', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
