# Generated by Django 2.0.3 on 2019-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='sort',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
